source 'https://rubygems.org'

ruby '2.1.2'

gem 'heroku-bouncer'
gem 'sinatra-contrib'
gem 'thin'
gem 'slim'
gem 'compass'
gem 'http_parser.rb', github: 'tmm1/http_parser.rb', branch: 'latest-upstream'
gem 'eventmachine'
gem 'em-http-request'
gem 'json'
gem 'rack-flash3'
gem "stethoscope", github: 'raulb/stethoscope'
